# Generated by Django 2.0.4 on 2018-04-15 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_profile_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile_name',
            new_name='profile_image',
        ),
    ]
